# Generated by Django 6.0.6 on 2026-06-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Books', 'Books'), ('Clothing', 'Clothing'), ('Home', 'Home'), ('Sports', 'Sports'), ('Beauty', 'Beauty')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['-created_at', '-id'], name='products_pr_created_e6f9fc_idx'), models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'), models.Index(fields=['category', '-created_at', '-id'], name='products_pr_categor_9a7517_idx')],
            },
        ),
    ]
